joint_limits:
  shoulder:
    has_velocity_limits: true
    max_velocity: 1.396
    has_acceleration_limits: true
    max_acceleration: 0.262
  elbow:
    has_velocity_limits: true
    max_velocity: 1.396
    has_acceleration_limits: true
    max_acceleration: 0.262
  wrist_pitch:
    has_velocity_limits: true
    max_velocity: 1.396
    has_acceleration_limits: true
    max_acceleration: 0.262
  wrist_rot:
    has_velocity_limits: true
    max_velocity: 1.745
    has_acceleration_limits: true
    max_acceleration: 0.262
  grip:
    has_velocity_limits: true
    max_velocity: 1.396
    has_acceleration_limits: true
    max_acceleration: 0.262
  base_rot:
    has_velocity_limits: true
    max_velocity: 1.745
    has_acceleration_limits: true
    max_acceleration: 0.262
